Repository c3rb3ru5d3d53c/binlex, pull requests merged in 2022-04, with the labels that each got.

#55 54 entropy uses map to store frequncies a vector should be used
  src/common.cpp
Labels: enhancement

#57 Bug fix for decompiler section offset
  .gitignore
  src/decompiler.cpp
Labels: bug, doing

#53 Merging current pe_cil branch, removing function definitions from header files and beginning of feature parity with x86/x86-64 decompiler.
  CMakeLists.txt
  include/args.h
  include/cil.h
  include/pe-dotnet.h
  include/pe.h
  src/binlex.cpp
  src/cil.cpp
  src/pe-dotnet.cpp
  src/pe.cpp
Labels: enhancement, doing

#64 bug fixed, script will now overwrite all files
  docker.sh
Labels: bug

#65 Add initial support for auto detecting file types
  .gitignore
  CMakeLists.txt
  include/args.h
  include/auto.h
  src/auto.cpp
  src/binlex.cpp
Labels: enhancement

#71 fix safe directory install errors
  Makefile
Labels: enhancement

#68 Disassembler optimization
  include/blelf.h
  include/common.h
  include/decompiler.h
  include/pe.h
  include/raw.h
  src/args.cpp
  src/binlex.cpp
  src/blelf.cpp
  src/pe.cpp
  src/raw.cpp
  tests/coverage.py
  tests/ida_baseline.zip
Labels: enhancement, doing

#63 Merge CIL Cleanup to Staging
  .appveyor.yml
  CMakeLists.txt
  Makefile
  include/args.h
  include/cil.h
  include/pe-dotnet.h
  include/pe.h
  scripts/.gitignore
  scripts/build.ps1
  scripts/learn.py
  setup.py
  src/binlex.cpp
  src/cil.cpp
  src/pe-dotnet.cpp
  src/pe.cpp
Labels: enhancement, doing

#74 sped up coverage script
  tests/coverage.py
Labels: enhancement

#67 Base api, files pulled from blserver branch
  .dockerignore
  .gitignore
  README.md
  docker.sh
  docker/.gitignore
  docker/blapi/.gitignore
  docker/blapi/Dockerfile
  docker/blapi/README.md
  docker/blapi/blapi
  docker/blapi/libblapiserver/__init__.py
  docker/blapi/libblapiserver/apis/__init__.py
  docker/blapi/libblapiserver/apis/binlex.py
  docker/blapi/libblapiserver/apis/mongodb.py
  docker/blapi/libblapiserver/apis/yara.py
  docker/blapi/libblapiserver/auth.py
  docker/blapi/libblapiserver/main.py
  docker/blapi/setup.py
  docker/blapi/start.sh
  docker/blapi/uwsgi.ini
  docker/bldb/.gitignore
  docker/bldb/Dockerfile
  docker/bldb/README.md
  docker/bldb/bldb
  docker/bldb/requirements.txt
  docker/bldb/setup.py
  docker/bldb/start.sh
  docker/bldec/.gitignore
  docker/bldec/Dockerfile
  docker/bldec/README.md
  docker/bldec/bldec
  docker/bldec/setup.py
  docker/bldec/start.sh
  docker/bljupyter/Dockerfile
  docker/docker-compose.yml
  docker/mongodb/Dockerfile
  docker/rabbitmq/Dockerfile
  lib/python/libblapi/.gitignore
  lib/python/libblapi/README.md
  lib/python/libblapi/libblapi/__init__.py
  lib/python/libblapi/libblapi/amqp.py
  lib/python/libblapi/libblapi/minio.py
  lib/python/libblapi/libblapi/mongodb.py
  lib/python/libblapi/setup.py
  pyproject.toml
  schema.js
  tests.py
Labels: enhancement, doing

#61 23 tlsh fuzzy hashing
  .appveyor.yml
  CMakeLists.txt
  README.md
  include/blelf.h
  include/common.h
  include/file.h
  include/pe.h
  src/blelf.cpp
  src/common.cpp
  src/file.cpp
  src/pe.cpp
Labels: enhancement, doing

#66 41 Auto
  .gitignore
  CMakeLists.txt
  include/args.h
  include/auto.h
  src/args.cpp
  src/auto.cpp
  src/binlex.cpp
Labels: enhancement, doing
