Repository c3rb3ru5d3d53c/binlex, pull requests merged in 2022-05, with the labels that each got.

#77 Merge Staging to Milestone Branch
  .appveyor.yml
  .gitignore
  CMakeLists.txt
  README.md
  include/args.h
  include/auto.h
  include/blelf.h
  include/common.h
  include/file.h
  include/pe.h
  include/raw.h
  src/args.cpp
  src/auto.cpp
  src/binlex.cpp
  src/blelf.cpp
  src/common.cpp
  src/file.cpp
  src/pe.cpp
  src/raw.cpp
  tests/tests.py
Labels: enhancement

#86 Update auto detection
  include/auto.h
  include/pe-dotnet.h
  include/pe.h
  src/auto.cpp
  src/binlex.cpp
  src/pe-dotnet.cpp
  src/pe.cpp
Labels: enhancement, doing

#88 Disassembler Optimization (fix memory leak)
  .appveyor.yml
  include/common.h
  include/decompiler.h
  src/blelf.cpp
  src/cil.cpp
  src/common.cpp
  src/decompiler.cpp
  src/pe.cpp
  tests/coverage.py
Labels: bug, enhancement, doing

#89 Upload sample endpoint
  Makefile
  docker/blapi/libblapiserver/apis/binlex.py
Labels: enhancement

#90 rabbitmq changes into staging
  docker.sh
  docker/bldb/bldb
  lib/python/libblapi/libblapi/amqp.py
Labels: enhancement, doing

#95 Feature parity with x86/x86-64 decompiler.
  include/cil.h
  src/binlex.cpp
  src/cil.cpp
Labels: enhancement, doing

#98 Fixing signed-ness bug for hex-byte outputs resulting in crash.
  include/cil.h
  src/cil.cpp
Labels: enhancement, doing

#99 Fixing output for pe:cil mode parameter.
  src/binlex.cpp
  src/cil.cpp
Labels: enhancement, doing

#101 remove unused declaration
  include/decompiler.h
Labels: enhancement, doing

#102 Fix for prefix instructions not being processed and adding append to file JSON output.
  src/cil.cpp
Labels: doing

#104 Adding support for function traits.
  include/cil.h
  src/auto.cpp
  src/binlex.cpp
  src/cil.cpp
Labels: bug, doing

#105 Using proper mode for 64 bit files
  docker/bldec/bldec
Labels: enhancement, doing

#106 pybinlex docker image as base for bldec
  docker.sh
  docker/bldec/Dockerfile
  docker/pybinlex/Dockerfile
Labels: enhancement, doing

#111 Bldec
  docker.sh
  docker/blapi/start.sh
  lib/python/libblapi/libblapi/amqp.py
Labels: enhancement, doing

#117 TLSH Trait Hashing
  bindings/python/common.cpp
  docs/html/classbinlex_1_1Common-members.html
  docs/html/classbinlex_1_1Common.html
  docs/html/classbinlex_1_1Decompiler-members.html
  docs/html/classbinlex_1_1Decompiler.html
  docs/html/classbinlex_1_1ELF-members.html
  docs/html/classbinlex_1_1ELF.html
  docs/html/classbinlex_1_1PE-members.html
  docs/html/classbinlex_1_1PE.html
  docs/html/classbinlex_1_1Raw-members.html
  docs/html/classbinlex_1_1Raw.html
  docs/html/common_8h_source.html
  docs/html/functions.html
  docs/html/functions_func.html
  docs/html/menudata.js
  docs/html/search/all_4.js
  docs/html/search/all_5.js
  docs/html/search/all_6.js
  docs/html/search/all_7.js
  docs/html/search/all_8.js
  docs/html/search/all_9.js
  docs/html/search/all_a.js
  docs/html/search/all_b.js
  docs/html/search/all_c.js
  docs/html/search/all_d.js
  docs/html/search/classes_0.js
  docs/html/search/classes_1.js
  docs/html/search/classes_2.js
  docs/html/search/classes_3.js
  docs/html/search/classes_4.js
  docs/html/search/classes_5.js
  docs/html/search/classes_6.js
  docs/html/search/classes_7.js
  docs/html/search/functions_0.js
  docs/html/search/functions_1.js
  docs/html/search/functions_2.js
  docs/html/search/functions_3.js
  docs/html/search/functions_4.js
  docs/html/search/functions_5.js
  docs/html/search/functions_6.js
  docs/html/search/functions_7.js
  docs/html/search/functions_8.js
  docs/html/search/functions_9.js
  docs/html/search/functions_a.js
  docs/html/search/functions_b.js
  docs/html/search/namespaces_0.js
  docs/html/search/pages_0.js
  docs/html/search/searchdata.js
  include/common.h
  src/cil.cpp
  src/common.cpp
  src/decompiler.cpp
Labels: enhancement

#121 119 compiler warnings
  include/cil.h
  include/decompiler.h
  include/pe-dotnet.h
  src/cil.cpp
  src/decompiler.cpp
  src/pe-dotnet.cpp
  src/pe.cpp
Labels: enhancement

#123 Remove Decompiler.Setup Method
  README.md
  bindings/python/blelf.cpp
  bindings/python/common.cpp
  bindings/python/decompiler.cpp
  bindings/python/pe.cpp
  bindings/python/raw.cpp
  include/args.h
  include/blelf.h
  include/cil.h
  include/common.h
  include/decompiler.h
  include/decompilerbase.h
  include/file.h
  include/pe.h
  include/raw.h
  src/args.cpp
  src/auto.cpp
  src/binlex.cpp
  src/blelf.cpp
  src/cil.cpp
  src/decompiler.cpp
  src/decompilerbase.cpp
  src/file.cpp
  src/pe-dotnet.cpp
  src/pe.cpp
  src/raw.cpp
  tests/tests.py
Labels: enhancement

#124 60 dupe traits
  include/decompiler.h
  src/decompiler.cpp
Labels: bug

#127 Compile on MSVC
  .appveyor.yml
  CMakeLists.txt
  include/cil.h
  include/file.h
  include/raw.h
  include/sha256.h
  src/blelf.cpp
  src/common.cpp
  src/pe.cpp
  src/sha256.c
Labels: enhancement

#132 Fix for building on macOS.
  CMakeLists.txt
  include/cil.h
Labels: enhancement
